version = 0.1
[default.deploy.parameters]
stack_name = "java-lambda-function-sam-cli-deploy"
resolve_s3 = true
s3_prefix = "java-lambda-function-sam-cli-deploy"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
